

def create_new_project(name):
    result = INITIAL_PROJECT.copy()
    result['settings']['ADMIN_SITE_HEADER'] = name
    result['settings']['EMAIL_SUBJECT_PREFIX'] = '[{}] '.format(name)
    return result


INITIAL_PROJECT = {
    'version': '0.1',
    'ui': {'models_view': 'full'},  # TODO: think maybe ui better be on some ~/.djangoprototyper.json
    'settings': {
        'ADMIN_SITE_HEADER': 'Barbecook',
        'DEFAULT_FROM_EMAIL': 'support@barbecook.com',
        'EMAIL_SUBJECT_PREFIX': '[barbecook] ',
        'LANGUAGE_CODE': 'en-us',
        'TIME_ZONE': 'Europe/Brussels',
        'USE_I18N': True,
        'USE_L10N': True,
        'django_contrib_apps': ['django.contrib.admin',
                                'django.contrib.auth',
                                'django.contrib.contenttypes',
                                'django.contrib.sessions',
                                'django.contrib.messages',
                                'django.contrib.staticfiles']},
    'apps': [{'models': [{'admin': {'generate': True},
              'fields': [{'name': 'name', 'type': 'CharField'}],
              'name': 'Holiday'},
             {'admin': {'generate': True},
              'fields': [{'name': 'holiday', 'type': 'ForeignKey'},
                         {'name': 'from_date', 'type': 'DateField'},
                         {'name': 'to_date', 'type': 'DateField'}],
              'name': 'HolidayDates'},
             {'admin': {'generate': True},
              'fields': [{'name': 'name', 'type': 'CharField'},
                         {'name': 'km',
                          'type': 'PositiveIntegerField'},
                         {'name': 'max_altitude',
                          'type': 'PositiveIntegerField'},
                         {'name': 'ski_tracks',
                          'type': 'PositiveSmallIntegerField'},
                         {'name': 'ski_elevators',
                          'type': 'PositiveSmallIntegerField'},
                         {'name': 'area_map', 'type': 'FileField'},
                         {'name': 'description',
                          'type': 'TextField'}],
              'name': 'SkiArea'},
             {'admin': {'generate': True},
              'fields': [{'name': 'name', 'type': 'CharField'},
                         {'name': 'address', 'type': 'TextField'},
                         {'name': 'contact_info',
                          'type': 'TextField'},
                         {'name': 'open_hours',
                          'type': 'TextField'}],
              'name': 'SkipassShop'},
             {'admin': {'generate': True},
              'fields': [{'name': 'area', 'type': 'ForeignKey'},
                         {'name': 'title', 'type': 'CharField'},
                         {'name': 'subtitle', 'type': 'CharField'},
                         {'name': 'public_price',
                          'type': 'DecimalField'},
                         {'name': 'description',
                          'type': 'TextField'}],
              'name': 'SkiPass'},
             {'admin': {'generate': True},
              'fields': [{'name': 'skipass', 'type': 'ForeignKey'},
                         {'name': 'period', 'type': 'ForeignKey'},
                         {'name': 'price', 'type': 'DecimalField'}],
              'name': 'SkiPassPrice'},
             {'admin': {'generate': True},
              'fields': [{'name': 'name', 'type': 'CharField'},
                         {'name': 'skiarea', 'type': 'ForeignKey'},
                         {'name': 'country',
                          'type': 'CountryField'},
                         {'name': 'altitude',
                          'type': 'PositiveIntegerField'},
                         {'name': 'description',
                          'type': 'TextField'},
                         {'name': 'google_maps_url',
                          'type': 'CharField'}],
              'name': 'Destination'},
             {'admin': {'generate': True},
              'fields': [{'name': 'name', 'type': 'CharField'},
                         {'name': 'name_short',
                          'type': 'CharField'},
                         {'name': 'destination',
                          'type': 'ForeignKey'},
                         {'name': 'type', 'type': 'CharField'},
                         {'name': 'price_class',
                          'type': 'PositiveSmallIntegerField'},
                         {'name': 'tripadvisor_score',
                          'type': 'DecimalField'},
                         {'name': 'booking_score',
                          'type': 'DecimalField'},
                         {'name': 'description',
                          'type': 'FroalaField'},
                         {'name': 'location_details',
                          'type': 'FroalaField'},
                         {'name': 'address', 'type': 'TextField'},
                         {'name': 'open_hours',
                          'type': 'TextField'},
                         {'name': 'check_in', 'type': 'CharField'},
                         {'name': 'check_out', 'type': 'CharField'},
                         {'name': 'deposit', 'type': 'FroalaField'},
                         {'name': 'parking', 'type': 'FroalaField'},
                         {'name': 'linen_and_towels',
                          'type': 'FroalaField'},
                         {'name': 'tourist_tax',
                          'type': 'FroalaField'},
                         {'name': 'lat', 'type': 'DecimalField'},
                         {'name': 'lng', 'type': 'DecimalField'}],
              'name': 'Hotel'},
             {'admin': {'generate': True},
              'fields': [{'name': 'hotel', 'type': 'ForeignKey'},
                         {'name': 'name', 'type': 'CharField'},
                         {'name': 'picture', 'type': 'ImageField'},
                         {'name': 'pax',
                          'type': 'PositiveSmallIntegerField'},
                         {'name': 'bathrooms',
                          'type': 'PositiveSmallIntegerField'},
                         {'name': 'rooms',
                          'type': 'PositiveSmallIntegerField'},
                         {'name': 'single_bed',
                          'type': 'PositiveSmallIntegerField'},
                         {'name': 'double_bed',
                          'type': 'PositiveSmallIntegerField'},
                         {'name': 'bunk_bed',
                          'type': 'PositiveSmallIntegerField'},
                         {'name': 'couch_bed',
                          'type': 'PositiveSmallIntegerField'},
                         {'name': 'stars',
                          'type': 'PositiveSmallIntegerField'},
                         {'name': 'min_occupation',
                          'type': 'PositiveSmallIntegerField'},
                         {'name': 'description',
                          'type': 'TextField'}],
              'name': 'AcmdType'},
             {'admin': {'generate': True},
              'fields': [{'name': 'sort_order',
                          'type': 'PositiveIntegerField'},
                         {'name': 'name', 'type': 'CharField'}],
              'name': 'AmenityCategory'},
             {'admin': {'generate': True},
              'fields': [{'name': 'sort_order',
                          'type': 'PositiveIntegerField'},
                         {'name': 'category', 'type': 'ForeignKey'},
                         {'name': 'name', 'type': 'CharField'},
                         {'name': 'icon', 'type': 'ImageField'}],
              'name': 'Amenity'},
             {'admin': {'generate': True},
              'fields': [{'name': 'destination',
                          'type': 'ForeignKey'},
                         {'name': 'name', 'type': 'CharField'},
                         {'name': 'name_short',
                          'type': 'CharField'},
                         {'name': 'google_maps_url',
                          'type': 'CharField'},
                         {'name': 'contact_info',
                          'type': 'TextField'},
                         {'name': 'description',
                          'type': 'TextField'},
                         {'name': 'address', 'type': 'TextField'},
                         {'name': 'open_hours',
                          'type': 'TextField'}],
              'name': 'Shop'},
             {'admin': {'generate': True},
              'fields': [{'name': 'shop', 'type': 'ForeignKey'},
                         {'name': 'title', 'type': 'CharField'},
                         {'name': 'subtitle', 'type': 'CharField'},
                         {'name': 'public_price',
                          'type': 'DecimalField'},
                         {'name': 'quality',
                          'type': 'PositiveSmallIntegerField'}],
              'name': 'Equipment'},
             {'admin': {'generate': True},
              'fields': [{'name': 'name', 'type': 'CharField'},
                         {'name': 'start', 'type': 'DateField'},
                         {'name': 'end', 'type': 'DateField'}],
              'name': 'Period'}],
  'name': 'configuration'},
 {'models': [{'admin': {'generate': True},
              'fields': [{'name': 'sort_order',
                          'type': 'PositiveIntegerField'},
                         {'name': 'title', 'type': 'CharField'},
                         {'name': 'slug', 'type': 'SlugField'},
                         {'name': 'status', 'type': 'CharField'},
                         {'name': 'title_admin',
                          'type': 'CharField'},
                         {'name': 'hotel', 'type': 'ForeignKey'},
                         {'name': 'skiarea', 'type': 'ForeignKey'},
                         {'name': 'shop', 'type': 'ForeignKey'},
                         {'name': 'skipass_shop',
                          'type': 'ForeignKey'},
                         {'name': 'max_group_size',
                          'type': 'PositiveSmallIntegerField'},
                         {'name': 'price', 'type': 'DecimalField'},
                         {'name': 'price_striped',
                          'type': 'DecimalField'},
                         {'name': 'price_subtext',
                          'type': 'CharField'},
                         {'name': 'price_info',
                          'type': 'CharField'},
                         {'name': 'main_image',
                          'type': 'ImageField'},
                         {'name': 'short_description',
                          'type': 'TextField'},
                         {'name': 'warnings', 'type': 'TextField'},
                         {'name': 'timestamp_visible_start',
                          'type': 'DateTimeField'},
                         {'name': 'timestamp_visible_end',
                          'type': 'DateTimeField'},
                         {'name': 'timestamp_bookable_start',
                          'type': 'DateTimeField'},
                         {'name': 'timestamp_bookable_end',
                          'type': 'DateTimeField'}],
              'name': 'OfferCarousel'},
             {'admin': {'generate': True},
              'fields': [{'name': 'sort_order',
                          'type': 'PositiveIntegerField'},
                         {'name': 'offer', 'type': 'ForeignKey'},
                         {'name': 'picture',
                          'type': 'ImageField'}],
              'name': 'OfferCarouselSlide'},
             {'admin': {'generate': True},
              'fields': [{'name': 'polymorphic_ctype',
                          'type': 'ForeignKey'},
                         {'name': 'sort_order',
                          'type': 'PositiveIntegerField'},
                         {'name': 'offer', 'type': 'ForeignKey'}],
              'name': 'OfferBlock'},
             {'admin': {'generate': True},
              'fields': [{'name': 'polymorphic_ctype',
                          'type': 'ForeignKey'},
                         {'name': 'sort_order',
                          'type': 'PositiveIntegerField'},
                         {'name': 'offer', 'type': 'ForeignKey'},
                         {'name': 'offerblock_ptr',
                          'type': 'OneToOneField'},
                         {'name': 'title', 'type': 'CharField'},
                         {'name': 'text', 'type': 'FroalaField'},
                         {'name': 'picture',
                          'type': 'ImageField'},
                         {'name': 'picture_position',
                          'type': 'PositiveSmallIntegerField'}],
              'name': 'OfferImageBlock'},
             {'admin': {'generate': True},
              'fields': [{'name': 'polymorphic_ctype',
                          'type': 'ForeignKey'},
                         {'name': 'sort_order',
                          'type': 'PositiveIntegerField'},
                         {'name': 'offer', 'type': 'ForeignKey'},
                         {'name': 'offerblock_ptr',
                          'type': 'OneToOneField'},
                         {'name': 'title', 'type': 'CharField'},
                         {'name': 'text', 'type': 'FroalaField'}],
              'name': 'OfferTextBlock'},
             {'admin': {'generate': True},
              'fields': [{'name': 'polymorphic_ctype',
                          'type': 'ForeignKey'},
                         {'name': 'sort_order',
                          'type': 'PositiveIntegerField'},
                         {'name': 'offer', 'type': 'ForeignKey'},
                         {'name': 'offerblock_ptr',
                          'type': 'OneToOneField'},
                         {'name': 'title', 'type': 'CharField'}],
              'name': 'OfferCarouselBlock'},
             {'admin': {'generate': True},
              'fields': [{'name': 'sort_order',
                          'type': 'PositiveIntegerField'},
                         {'name': 'carousel', 'type': 'ForeignKey'},
                         {'name': 'title', 'type': 'CharField'},
                         {'name': 'picture',
                          'type': 'ImageField'}],
              'name': 'OfferCarouselBlockSlide'},
             {'admin': {'generate': True},
              'fields': [{'name': 'polymorphic_ctype',
                          'type': 'ForeignKey'},
                         {'name': 'sort_order',
                          'type': 'PositiveIntegerField'},
                         {'name': 'offer', 'type': 'ForeignKey'},
                         {'name': 'offerblock_ptr',
                          'type': 'OneToOneField'}],
              'name': 'OfferSkiAreaBlock'},
             {'admin': {'generate': True},
              'fields': [{'name': 'polymorphic_ctype',
                          'type': 'ForeignKey'},
                         {'name': 'sort_order',
                          'type': 'PositiveIntegerField'},
                         {'name': 'offer', 'type': 'ForeignKey'},
                         {'name': 'offerblock_ptr',
                          'type': 'OneToOneField'}],
              'name': 'OfferLocationBlock'},
             {'admin': {'generate': True},
              'fields': [{'name': 'slot',
                          'type': 'PositiveSmallIntegerField'},
                         {'name': 'slot_reversed',
                          'type': 'BooleanField'},
                         {'name': 'url', 'type': 'URLField'},
                         {'name': 'text', 'type': 'TextField'},
                         {'name': 'button_text',
                          'type': 'CharField'},
                         {'name': 'background',
                          'type': 'ImageField'}],
              'name': 'HomeTextBlock'},
             {'admin': {'generate': True},
              'fields': [{'name': 'slot',
                          'type': 'PositiveSmallIntegerField'},
                         {'name': 'slot_reversed',
                          'type': 'BooleanField'},
                         {'name': 'is_active',
                          'type': 'BooleanField'}],
              'name': 'HomeHelpBlock'},
             {'admin': {'generate': True},
              'fields': [{'name': 'key', 'type': 'CharField'},
                         {'name': 'type',
                          'type': 'PositiveSmallIntegerField'},
                         {'name': 'text', 'type': 'TextField'},
                         {'name': 'image', 'type': 'ImageField'}],
              'name': 'Chunk'}],
  'name': 'content'},
 {'models': [{'admin': {'generate': True},
              'fields': [{'name': 'order', 'type': 'ForeignKey'},
                         {'name': 'amount', 'type': 'DecimalField'},
                         {'name': 'user', 'type': 'ForeignKey'},
                         {'name': 'mollie_id', 'type': 'CharField'},
                         {'name': 'payment_method',
                          'type': 'CharField'},
                         {'name': 'status', 'type': 'CharField'},
                         {'name': 'charge_date',
                          'type': 'DateTimeField'},
                         {'name': 'cancel_date',
                          'type': 'DateTimeField'},
                         {'name': 'expired_date',
                          'type': 'DateTimeField'},
                         {'name': 'created',
                          'type': 'DateTimeField'}],
              'name': 'Deposit'}],
  'name': 'deposits'},
 {'models': [{'admin': {'generate': True},
              'fields': [{'name': 'title', 'type': 'CharField'},
                         {'name': 'parent',
                          'type': 'TreeForeignKey'},
                         {'name': 'timestamp',
                          'type': 'DateTimeField'},
                         {'name': 'lft',
                          'type': 'PositiveIntegerField'},
                         {'name': 'rght',
                          'type': 'PositiveIntegerField'},
                         {'name': 'tree_id',
                          'type': 'PositiveIntegerField'},
                         {'name': 'level',
                          'type': 'PositiveIntegerField'}],
              'name': 'Folder'},
             {'admin': {'generate': True},
              'fields': [{'name': 'title', 'type': 'CharField'},
                         {'name': 'image', 'type': 'ImageField'},
                         {'name': 'timestamp',
                          'type': 'DateTimeField'},
                         {'name': 'folder', 'type': 'ForeignKey'}],
              'name': 'Picture'}],
  'name': 'gallery'},
 {'models': [{'admin': {'generate': True},
              'fields': [{'name': 'email', 'type': 'EmailField'},
                         {'name': 'timestamp',
                          'type': 'DateTimeField'}],
              'name': 'Subscriber'}],
  'name': 'newsletter'},
 {'models': [{'admin': {'generate': True},
              'fields': [{'name': 'sort_order',
                          'type': 'PositiveIntegerField'},
                         {'name': 'title', 'type': 'CharField'},
                         {'name': 'slug', 'type': 'SlugField'},
                         {'name': 'status', 'type': 'CharField'},
                         {'name': 'title_admin',
                          'type': 'CharField'},
                         {'name': 'hotel', 'type': 'ForeignKey'},
                         {'name': 'skiarea', 'type': 'ForeignKey'},
                         {'name': 'shop', 'type': 'ForeignKey'},
                         {'name': 'skipass_shop',
                          'type': 'ForeignKey'},
                         {'name': 'max_group_size',
                          'type': 'PositiveSmallIntegerField'},
                         {'name': 'price', 'type': 'DecimalField'},
                         {'name': 'price_striped',
                          'type': 'DecimalField'},
                         {'name': 'price_subtext',
                          'type': 'CharField'},
                         {'name': 'price_info',
                          'type': 'CharField'},
                         {'name': 'main_image',
                          'type': 'ImageField'},
                         {'name': 'short_description',
                          'type': 'TextField'},
                         {'name': 'warnings', 'type': 'TextField'},
                         {'name': 'timestamp_visible_start',
                          'type': 'DateTimeField'},
                         {'name': 'timestamp_visible_end',
                          'type': 'DateTimeField'},
                         {'name': 'timestamp_bookable_start',
                          'type': 'DateTimeField'},
                         {'name': 'timestamp_bookable_end',
                          'type': 'DateTimeField'}],
              'name': 'Offer'},
             {'admin': {'generate': True},
              'fields': [{'name': 'offer', 'type': 'ForeignKey'},
                         {'name': 'included',
                          'type': 'BooleanField'},
                         {'name': 'sort_order',
                          'type': 'PositiveIntegerField'},
                         {'name': 'accommodation',
                          'type': 'ForeignKey'},
                         {'name': 'period', 'type': 'ForeignKey'},
                         {'name': 'price', 'type': 'DecimalField'}],
              'name': 'OfferAccommodation'},
             {'admin': {'generate': True},
              'fields': [{'name': 'offer', 'type': 'ForeignKey'},
                         {'name': 'included',
                          'type': 'BooleanField'},
                         {'name': 'sort_order',
                          'type': 'PositiveIntegerField'},
                         {'name': 'skipass', 'type': 'ForeignKey'}],
              'name': 'OfferSkipass'},
             {'admin': {'generate': True},
              'fields': [{'name': 'offer', 'type': 'ForeignKey'},
                         {'name': 'included',
                          'type': 'BooleanField'},
                         {'name': 'sort_order',
                          'type': 'PositiveIntegerField'},
                         {'name': 'equipment',
                          'type': 'ForeignKey'},
                         {'name': 'price', 'type': 'DecimalField'}],
              'name': 'OfferEquipment'},
             {'admin': {'generate': True},
              'fields': [{'name': 'title', 'type': 'CharField'}],
              'name': 'ExtraCategory'},
             {'admin': {'generate': True},
              'fields': [{'name': 'offer', 'type': 'ForeignKey'},
                         {'name': 'included',
                          'type': 'BooleanField'},
                         {'name': 'sort_order',
                          'type': 'PositiveIntegerField'},
                         {'name': 'title', 'type': 'CharField'},
                         {'name': 'category', 'type': 'ForeignKey'},
                         {'name': 'price', 'type': 'DecimalField'}],
              'name': 'OfferExtra'}],
  'name': 'offers'},
 {'models': [{'admin': {'generate': True},
              'fields': [{'name': 'image', 'type': 'ImageField'},
                         {'name': 'group_title',
                          'type': 'CharField'},
                         {'name': 'group_subtitle',
                          'type': 'TextField'},
                         {'name': 'offer', 'type': 'ForeignKey'},
                         {'name': 'user', 'type': 'ForeignKey'},
                         {'name': 'timestamp',
                          'type': 'DateTimeField'},
                         {'name': 'status', 'type': 'CharField'},
                         {'name': 'notes', 'type': 'TextField'}],
              'name': 'Order'},
             {'admin': {'generate': True},
              'fields': [{'name': 'order', 'type': 'ForeignKey'},
                         {'name': 'user', 'type': 'ForeignKey'},
                         {'name': 'data', 'type': 'TextField'},
                         {'name': 'timestamp',
                          'type': 'DateTimeField'}],
              'name': 'Log'},
             {'admin': {'generate': True},
              'fields': [{'name': 'order', 'type': 'ForeignKey'},
                         {'name': 'owner', 'type': 'ForeignKey'},
                         {'name': 'name', 'type': 'CharField'},
                         {'name': 'accommodation',
                          'type': 'ForeignKey'},
                         {'name': 'skipass', 'type': 'ForeignKey'},
                         {'name': 'equipment',
                          'type': 'ForeignKey'},
                         {'name': 'deposit', 'type': 'ForeignKey'},
                         {'name': 'locked_by',
                          'type': 'ForeignKey'},
                         {'name': 'timestamp',
                          'type': 'DateTimeField'}],
              'name': 'Traveler'},
             {'admin': {'generate': True},
              'fields': [{'name': 'order', 'type': 'ForeignKey'},
                         {'name': 'accommodation',
                          'type': 'OneToOneField'},
                         {'name': 'num_people',
                          'type': 'PositiveIntegerField'}],
              'name': 'OrderAccommodation'}],
  'name': 'orders'},
 {'models': [{'admin': {'generate': True},
              'fields': [{'name': 'offer', 'type': 'ForeignKey'},
                         {'name': 'period', 'type': 'ForeignKey'},
                         {'name': 'min_price',
                          'type': 'DecimalField'},
                         {'name': 'start', 'type': 'DateField'},
                         {'name': 'end', 'type': 'DateField'},
                         {'name': 'duration', 'type': 'CharField'},
                         {'name': 'start_month',
                          'type': 'PositiveIntegerField'},
                         {'name': 'end_month',
                          'type': 'PositiveIntegerField'},
                         {'name': 'group_min',
                          'type': 'PositiveIntegerField'},
                         {'name': 'group_max',
                          'type': 'PositiveIntegerField'},
                         {'name': 'destination',
                          'type': 'ForeignKey'},
                         {'name': 'country',
                          'type': 'CountryField'}],
              'name': 'SearchIndex'}],
  'name': 'search'},
 {'models': [{'admin': {'generate': True},
              'fields': [{'name': 'password', 'type': 'CharField'},
                         {'name': 'last_login',
                          'type': 'DateTimeField'},
                         {'name': 'is_superuser',
                          'type': 'BooleanField'},
                         {'name': 'email', 'type': 'EmailField'},
                         {'name': 'first_name',
                          'type': 'CharField'},
                         {'name': 'last_name', 'type': 'CharField'},
                         {'name': 'image', 'type': 'ImageField'},
                         {'name': 'is_active',
                          'type': 'BooleanField'},
                         {'name': 'date_joined',
                          'type': 'DateTimeField'},
                         {'name': 'facebook_id',
                          'type': 'CharField'},
                         {'name': 'phone', 'type': 'CharField'},
                         {'name': 'address', 'type': 'CharField'},
                         {'name': 'postal_code',
                          'type': 'CharField'},
                         {'name': 'city', 'type': 'CharField'},
                         {'name': 'country',
                          'type': 'CountryField'},
                         {'name': 'language', 'type': 'CharField'},
                         {'name': 'birthdate', 'type': 'DateField'},
                         {'name': 'gender', 'type': 'CharField'}],
              'name': 'User'}],
  'name': 'users'}],
}