export const DJANGO_CONTRIB_APPS = {
    'admin': ['LogEntry'],
    'admindocs': [],
    'auth': ['AbstractBaseUser', 'AbstractUser', 'Group', 'Permission', 'PermissionsMixin', 'User'],
    'contenttypes': ['ContentType'],
    'flatpages': ['FlatPage'],
    'gis': [],
    'humanize': [],
    'messages': [],
    'postgres': [],
    'redirects': ['Redirect'],
    'sessions': ['AbstractBaseSession', 'Session'],
    'sitemaps': [],
    'sites': ['Site'],
    'staticfiles': [],
    'syndication': [],
}
